version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: transport-backend
    networks:
      - transport-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: transport-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - transport-net

networks:
  transport-net:
    driver: bridge